### ISSUE TITLE
Planilha MastoAves

### ISSUE THREAD

**Issue by pardalismitis** [ICMBio-CENAP/Programa-Monitora-Florestal-Global#1]
@elildojr pode disponibilizar:

- planilha consolidada mastoaves até 2019 - FINAL.csv
- Dados_Florestal_14a18_disponibilizacao.csv

**Comment by elildojr** [comment]
[Dados_Florestal_14a18_disponibilizacao.csv](https://github.com/ICMBio-CENAP/Programa-Monitora-Florestal-Global/files/8482380/Dados_Florestal_14a18_disponibilizacao.csv)
[Planilha consolidada mastoaves até 2019 - FINAL.csv](https://github.com/ICMBio-CENAP/Programa-Monitora-Florestal-Global/files/8482381/Planilha.consolidada.mastoaves.ate.2019.-.FINAL.csv)
